### ISSUE TITLE
Bisa dibuatkan function sendiri aja, misal private fun observe. Biar codingan bisa lebih rapi

### ISSUE THREAD

**Issue by anggapamb** [bennohan/MyNotes#3]
https://github.com/bennohan/MyNotes/blob/c47a4ca098827f46f61af47ba781aa77bb0e6844/app/src/main/java/com/example/mynotes/ui/register/RegisterActivity.kt#L52-L76

**Comment by bennohan** [comment]
private fun observe(){
        lifecycleScope.launch {
            repeatOnLifecycle(Lifecycle.State.STARTED) {
                launch {
                    viewModel.apiResponse.collect {
                        when (it.status) {
                            ApiStatus.LOADING -> loadingDialog.show("Register in")
                            ApiStatus.SUCCESS -> {
                                tos(it.message ?: "Berhasil Register")
                                loadingDialog.dismiss()
                                openActivity<HomeActivity>()
                                finish()
                            }
                            ApiStatus.ERROR -> {
                                disconnect(it)
                            }
                            ApiStatus.EXPIRED -> {

                            }
                            else -> loadingDialog.setResponse("Else")
//                            else -> loadingDialog.setResponse(it.message ?: return@collect)
                        }
                    }
                }
            }
        }

    }
